services:
  postgres_db:
    image: postgres:15
    container_name: shop_system_postgres

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - shop_net

  api:
    container_name: shop_system_api_dev

    build:
      context: .
      dockerfile: apps/api/Dev.dockerfile

    ports:
      - "${PORT:-3000}:3000"

    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages

      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./package.json:/app/package.json

      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/packages/dto/node_modules

    depends_on:
      - postgres_db

    env_file:
      - .env
      - ./apps/api/.env

    networks:
      - shop_net

networks:
  shop_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local