name: CI/CD (Docker Compose)

on:
  push:
    branches: [ main, master, feature/* ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "BASE_URL=http://web:5173" >> .env
          echo "API_URL=http://api:3000" >> .env
          echo "CI=true" >> .env

          echo "POSTGRES_USER=shop_user" >> .env
          echo "POSTGRES_PASSWORD=shop_pass" >> .env
          echo "POSTGRES_DB=shop_db" >> .env

          echo "DATABASE_URL=postgresql://shop_user:shop_pass@postgres_db:5432/shop_db?schema=public" >> .env
          
          touch apps/api/.env
          touch apps/web/.env
      - name: Start Services and Seed Database
        run: |
    
          docker compose --profile testing up -d --build web api postgres_db

          sleep 15

          docker compose exec -T api npx prisma db seed    

      - name: Run Tests via Docker Compose
        run: docker compose --profile testing run tests
        
      - name: Upload Raw Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-raw
          path: tests/allure-results/
          retention-days: 15